language: node_js
node_js: 12.18.3
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_1a747b613118_key -iv $encrypted_1a747b613118_iv
  -in id_rsa_travis.enc -out ~/.ssh/id_rsa_travis -d
- chmod 600 ~/.ssh/id_rsa_travis
- echo "before_install"
install:
- echo "install"
script: true
after_success:
- "./docker.sh"
- echo "after_success"
addons:
  ssh_known_hosts: 49.235.241.244
dd:
  secure: YNdxK1CyfFqjzbVa9vPCvas6z+QPV/so52iu207apLVW+GB5XnkZi5dsDsA//P2J5nPklayUp8sBt4DKwOQ1NLaiBAIW0TnWhIBajMIqOx7QPDNeRl9E6kqS6C4A9sfiKY+GJJtOhia5orKUwyArOQs0fAMBe1O8Ln5i/jgtB+qBRZswtI6f1kshbVhnVGU/pN7VLT4mRJPv+ptKVZon6YW6jh/3pPU3XdMUBERb4wxi6LwRkgbllg1NgvD/1AeRTQTYsPmmjJX1S6BPidAr5/uDxrtVVfUQzSpUqAGvH/DoQqAFy4o9+7OAzG4Fgn+3+0UqLHLECAZKBhp5um/YbAhanQPfmsTjTTO+bqAf66l9g9QQwYxgQrdV4L70BkD5rpfAyBtpLG47bZdjjyUBIE7DrSoEPZrQvYjy6VNUO3Uwg+lXXShVkh5M/5uukTwmUr7Jx1hz4yW23MY87qU0g/w7O2l4eT9ULzKxAAnJvNEksCYY1rtRVnzPr0np02t4UCx3143DpJ+nnghV+GtJwawJrPOaImKnIn0ytPSHo6EgaetkiBKAF0qnrtz+mXth0S1a1jk8cUut/QosUX1yQYtRFyh4rPBLoExbBZL6szf+tqRFgQT67JONVqfw/hzxh/yYkNxtKUlCLBz0rXjVOLgE3TUYt/VBnXCtLnIBcFw=
