language: node_js
node_js: 12.18.3
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_1a747b613118_key -iv $encrypted_1a747b613118_iv
  -in id_rsa_travis.enc -out ~/.ssh/id_rsa_travis -d
- chmod 600 ~/.ssh/id_rsa_travis
- echo "before_install"
install:
- echo "install"
script: true
after_success:
- "./docker.sh"
- echo "after_success"
addons:
  ssh_known_hosts: 49.235.241.244
env:
  global:
  - secure: HavkEhT94NdhgzhUr6Ga74tGm5f1qhC3yD5MicOgS1Gb11p1C+04vbyuF0Em3GvHdFrKSkxgC+tjg/B5F6Uq/hvZgeUKbwSgw2RPUN7RbyZ0BD1Jsh/Tv1oFUL/ELp5saWcSw2h8mMLydhCZu3vc3lgRREjgiXGFK/+k/VZt6VELQ7t54bt401V5VvYRDOfUeIwkqquefmLaJs7u6HVQHBr+7lMcdoYSz9ZsUFTVJu0xl6yDND/1eDSj1Xz+6ffqbHUOVvsNuT4SCP9meuouHyM644OlMvbMLP05QO+J2/Q+PDK5evcEOvN7NctZ3t76UiPrKECZrnWoKw2jc6v7D7hKqqAborc4RoDWJBTMVj/kc1cI9XMRjZWrQtvYAV+uz5FktzTzwMtnMoNllCKs6z9SpoDDe99oZnZ/GZK+AWE1vyQxcN9BCLnKDYcN+hotCBp9Et8j2tt8qN1I/LTCyvd8Eh1Bf5zjKM+1KdjVgIMdBCx9+wJai6tmKnbPBNhPbWvxXcnfF+1aVjKCJeNGMFsGpoZqOWZn7O9x6l50izHKw4JmCcYxBWRNRcdvmhceuYQKb0sfOr2EmEGNyBmURuCxedCN4qi3lIPX2xrnMRXMqlxYN0sOxFY3dsGkUfZN4CjBufYa2+Dl66qeulA3zkbAlnv2sgprBjUkVKoUaQU=
